CREATE TABLE  "ARTICULO" 
   (	"ID_ARTICULO" NUMBER(10,0) NOT NULL ENABLE, 
	"ARTICULO" VARCHAR2(900) NOT NULL ENABLE, 
	"ID_LEY" NUMBER(10,0), 
	 CONSTRAINT "ARTICULO_PK" PRIMARY KEY ("ID_ARTICULO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "ARTICULO" ADD CONSTRAINT "ARTICULO_FK" FOREIGN KEY ("ID_LEY")
	  REFERENCES  "LEY" ("ID_LEY") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_ARTICULO" 
  before insert on "ARTICULO"               
  for each row  
begin   
  if :NEW."ID_ARTICULO" is null then 
    select "ARTICULO_SEQ".nextval into :NEW."ID_ARTICULO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_ARTICULO" ENABLE
/