CREATE TABLE  "INCISO" 
   (	"ID_INCISO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER(10,0) NOT NULL ENABLE, 
	"INCISO" VARCHAR2(25) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(800) NOT NULL ENABLE, 
	 CONSTRAINT "INCISO_PK" PRIMARY KEY ("ID_INCISO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "INCISO" ADD CONSTRAINT "INCISO_FK" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES  "ARTICULO" ("ID_ARTICULO") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_INCISO" 
  before insert on "INCISO"               
  for each row  
begin   
  if :NEW."ID_INCISO" is null then 
    select "INCISO_SEQ".nextval into :NEW."ID_INCISO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_INCISO" ENABLE
/