CREATE TABLE  "LEY_EVALUADA" 
   (	"ID_LEY_EVALUADA" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER(10,0), 
	"ID_ARTICULO" NUMBER(10,0), 
	"DESCRIPCION" NVARCHAR2(800), 
	"CUMPLE" NUMBER(10,0), 
	"SANCION" VARCHAR2(800), 
	"PLAZO_DE_IMPLEMENTACION" DATE, 
	"SANCION_FINAL" VARCHAR2(800), 
	 CONSTRAINT "LEY_EVALUADA_PK" PRIMARY KEY ("ID_LEY_EVALUADA")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "LEY_EVALUADA" ADD CONSTRAINT "ARTICULO_EV_FK" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES  "ARTICULO" ("ID_ARTICULO") ENABLE
/
ALTER TABLE  "LEY_EVALUADA" ADD CONSTRAINT "EMPRESA_EVALUADA_FK" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES  "EMPRESA" ("ID_EMPRESA") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_LEY_EVALUADA" 
  before insert on "LEY_EVALUADA"               
  for each row  
begin   
  if :NEW."ID_LEY_EVALUADA" is null then 
    select "LEY_EVALUADA_SEQ1".nextval into :NEW."ID_LEY_EVALUADA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_LEY_EVALUADA" ENABLE
/