CREATE TABLE  "RESPALDO" 
   (	"ID_RESPALDO" NUMBER NOT NULL ENABLE, 
	"ID_LEY_EVALUDA" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(1000) NOT NULL ENABLE, 
	"DOCUMENTO_RESPALDO" BLOB NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(1000), 
	"MIM_TYPE" VARCHAR2(1000), 
	"LAST_UPDATE_DATE" DATE, 
	"CHARSET" VARCHAR2(1000), 
	 CONSTRAINT "RESPALDO_PK" PRIMARY KEY ("ID_RESPALDO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "RESPALDO" ADD CONSTRAINT "RESPALDO_LEY_EVALUADA_FK" FOREIGN KEY ("ID_LEY_EVALUDA")
	  REFERENCES  "LEY_EVALUADA" ("ID_LEY_EVALUADA") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_RESPALDO" 
  before insert on "RESPALDO"               
  for each row  
begin   
  if :NEW."ID_RESPALDO" is null then 
    select "RESPALDO_SEQ2".nextval into :NEW."ID_RESPALDO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_RESPALDO" ENABLE
/